### PR TITLE
Create index.js

### PR DESCRIPTION
**Pull request by fatihcalis**

### CODE REVIEW

**Comment by fatihcalis** [comment]
The conversation related to this pull request can be found on this [Slack channel]( https:\/\/slack.com\/app_redirect?channel=C066LDUD07P&team=T03KRF3G92S)

**Comment by fatihcalis** [comment]
comment

**Comment by fatihcalis** [comment]
comment 1

**Comment by fatihcalis** [comment]
comment 2

**Review by insanicly — APPROVED** [review]

**Review by insanicly — APPROVED** [review]

**Comment by fatihcalis** [comment]
fatih
calis

**Comment by fatihcalis** [comment]
bu comment `quote` içerir.

**Pull request closed without merging**
